### ISSUE TITLE
Update for Moodle 3.8

### ISSUE THREAD

**Issue by luisdev** [TheMatrixan/vscode-moodle-snippets#1]
Please update the code for Moodle 3.8.
If no update is required then update the documentation to indicate that the current version is still suitable for Moodle 3.8.
Thanks

**Comment by TheMatrixan** [comment]
I haven't been working with this technology for a long time, so I cannot say if snippets from this plugin, are correct for version 3.8. If you want to, you can create PR and I will review and merge it as soon as possible.
